name: Main Pipeline

on:
    push:
        branches:
            - main

jobs:
    reusable-build:
        uses: ./.github/workflows/reusable-build.yml
        with:
            python_version: 3.13
            run_test: true

    reusable-docker:
        needs: [reusable-build]
        uses: ./.github/workflows/reusable-docker.yml
        with: 
            image_name: latest
            tag: sha-${{github.sha}}
        secrets: 
            DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    deploy:
        needs: [reusable-docker]
        runs-on: ubuntu-latest

        environment:
            name: production

        steps:
            - name: Print
              run: echo "Deploying image ${{ needs.reusable-docker.outputs.image_url }} to production"




    
