name: PR pipeline

on:
    pull_request:
        branches: [main]
        types:
            - opened
            - synchronize


jobs:
    reusable-build:
        uses: ./.github/workflows/reusable-build.yml
        with:
            python_version: 3.13
            run_test: true

    pr-comment:
        runs-on: ubuntu-latest
        needs: [reusable-build]
        steps:
            - name: print summary
              run: echo "PR checks passed for branch is ${{ github.head_ref }}"
